export const jewel = [
  {
    id: "jewel001",
    category: "Diamond Ring",
    name: "Solitaire Diamond Ring",
    price: 95000,
    image_url:
      "https://www.tanishq.co.in/on/demandware.static/-/Sites-Tanishq-site-catalog/default/dw7773c9b5/All%20Earrings%2040.png",
  },
  {
    id: "jewel002",
    category: "Diamond Ring",
    name: "Elegant Halo Diamond Ring",
    price: 75000,
    image_url:
      "https://png.pngtree.com/png-vector/20240514/ourlarge/pngtree-a-diamond-engagement-ring-with-halo-setting-depicted-in-clipart-style-png-image_12447205.png",
  },
  {
    id: "jewel003",
    category: "Diamond Ring",
    name: "Vintage Diamond Ring",
    price: 88000,
    image_url:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSG1nPY02gnOvkFzWwrvMWgZ7-JJ2nJzOu15Q&s",
  },
  {
    id: "jewel004",
    category: "Diamond Ring",
    name: "Princess Cut Diamond Ring",
    price: 67000,
    image_url:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVFpRamy4boZc9ECo2pf_K1XcPVfXJ8viEkg&s",
  },
  {
    id: "jewel005",
    category: "Diamond Ring",
    name: "Rose Gold Diamond Ring",
    price: 92000,
    image_url:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQj1xP0R5ZhH5hyOUjuu7-laFJMXeg2xWzaMA&s",
  },
  {
    id: "jewel006",
    category: "Diamond Ring",
    name: "Modern Diamond Ring",
    price: 89000,
    image_url:
      "https://auratenewyork.com/cdn/shop/files/7_dbfd214c-db4e-4114-bbe9-f25d47f4cc27_1200x.png?v=1714506552",
  },
  {
    id: "jewel007",
    category: "Diamond Ring",
    name: "Minimalist Diamond Ring",
    price: 74000,
    image_url:
      "https://i.pinimg.com/564x/cb/07/c9/cb07c9b193ba9356581fed770cca30bf.jpg",
  },
  {
    id: "jewel008",
    category: "Diamond Ring",
    name: "Floral Diamond Ring",
    price: 83000,
    image_url:
      "https://png.pngtree.com/png-vector/20240528/ourlarge/pngtree-an-elegant-engagement-ring-featuring-a-floral-design-and-adorned-with-png-image_12524728.png",
  },
  {
    id: "jewel009",
    category: "Diamond Ring",
    name: "Infinity Diamond Ring",
    price: 81000,
    image_url:
      "https://png.pngtree.com/png-clipart/20200606/ourmid/pngtree-diamonds-wedding-ring-eternity-ring-pave-from-a-white-gold-band-png-image_2220580.jpg",
  },
  {
    id: "jewel010",
    category: "Diamond Ring",
    name: "Classic Diamond Band",
    price: 58000,
    image_url:
      "https://image.similarpng.com/very-thumbnail/2021/07/Diamond-ring-isolated-on-transparent-background-PNG.png",
  },
  {
    id: "jewel011",
    category: "Gold Bracelet",
    name: "Classic Gold Bracelet",
    price: 55000,
    image_url:
      "https://image.similarpng.com/very-thumbnail/2020/10/Golden-bracelet-jewelry-on-transparent-background-PNG.png",
  },
  {
    id: "jewel012",
    category: "Gold Bracelet",
    name: "Elegant Twisted Gold Bracelet",
    price: 67000,
    image_url:
      "https://img.freepik.com/free-psd/beautiful-designed-gold-bracelet-isolated-transparent-background_191095-12415.jpg",
  },
  {
    id: "jewel013",
    category: "Gold Bracelet",
    name: "Curb Link Gold Bracelet",
    price: 72000,
    image_url:
      "https://auratenewyork.com/cdn/shop/products/AU-16_3e9350d1-dc8d-4842-8119-70da5d661c1b_1200x.png?v=1591048632",
  },
  {
    id: "jewel014",
    category: "Gold Bracelet",
    name: "Minimalist Gold Bangle",
    price: 68000,
    image_url:
      "https://w7.pngwing.com/pngs/162/1008/png-transparent-jewellery-bangle-earring-gold-gold-banner-miscellaneous-ring-bracelet.png",
  },
  {
    id: "jewel015",
    category: "Gold Bracelet",
    name: "Open Cuff Gold Bracelet",
    price: 65000,
    image_url:
      "https://img.freepik.com/free-psd/beautiful-designed-gold-bracelet-isolated-transparent-background_191095-12415.jpg",
  },
  {
    id: "jewel016",
    category: "Gold Bracelet",
    name: "Modern Gold Chain Bracelet",
    price: 71000,
    image_url:
      "https://png.pngtree.com/png-vector/20240809/ourmid/pngtree-elegant-plain-yellow-gold-women-s-bracelet-png-image_13420826.png",
  },
  {
    id: "jewel017",
    category: "Gold Bracelet",
    name: "Baroque Pearl Gold Bracelet",
    price: 86000,
    image_url: "https://example.com/images/baroque-pearl-gold-bracelet.jpg",
  },
  {
    id: "jewel018",
    category: "Gold Bracelet",
    name: "Twisted Rope Gold Bracelet",
    price: 64000,
    image_url: "https://example.com/images/twisted-rope-gold-bracelet.jpg",
  },
  {
    id: "jewel019",
    category: "Gold Bracelet",
    name: "Stackable Gold Bracelet Set",
    price: 93000,
    image_url: "https://example.com/images/stackable-gold-bracelet-set.jpg",
  },
  {
    id: "jewel020",
    category: "Gold Bracelet",
    name: "Delicate Chain Gold Bracelet",
    price: 32000,
    image_url: "https://example.com/images/delicate-chain-gold-bracelet.jpg",
  },
  {
    id: "jewel021",
    category: "Gold Pendant",
    name: "Heart-Shaped Gold Pendant",
    price: 35000,
    image_url: "https://example.com/images/heart-gold-pendant.jpg",
  },
  {
    id: "jewel022",
    category: "Gold Pendant",
    name: "Minimalist Gold Bar Pendant",
    price: 28000,
    image_url: "https://example.com/images/minimalist-gold-pendant.jpg",
  },
  {
    id: "jewel023",
    category: "Gold Pendant",
    name: "Infinity Gold Pendant",
    price: 45000,
    image_url: "https://example.com/images/infinity-gold-pendant.jpg",
  },
  {
    id: "jewel024",
    category: "Gold Pendant",
    name: "Tree of Life Gold Pendant",
    price: 40000,
    image_url: "https://example.com/images/tree-of-life-gold-pendant.jpg",
  },
  {
    id: "jewel025",
    category: "Gold Pendant",
    name: "Geometric Gold Pendant",
    price: 33000,
    image_url: "https://example.com/images/geometric-gold-pendant.jpg",
  },
  {
    id: "jewel026",
    category: "Gold Pendant",
    name: "Initials Gold Pendant",
    price: 41000,
    image_url: "https://example.com/images/initials-gold-pendant.jpg",
  },
  {
    id: "jewel027",
    category: "Gold Pendant",
    name: "Circle of Life Gold Pendant",
    price: 38000,
    image_url: "https://example.com/images/circle-of-life-gold-pendant.jpg",
  },
  {
    id: "jewel028",
    category: "Gold Pendant",
    name: "Locket Style Gold Pendant",
    price: 47000,
    image_url: "https://example.com/images/locket-gold-pendant.jpg",
  },
  {
    id: "jewel029",
    category: "Gold Pendant",
    name: "Star Gold Pendant",
    price: 37000,
    image_url: "https://example.com/images/star-gold-pendant.jpg",
  },
  {
    id: "jewel030",
    category: "Gold Pendant",
    name: "Feather Gold Pendant",
    price: 34000,
    image_url: "https://example.com/images/feather-gold-pendant.jpg",
  },
  {
    id: "jewel031",
    category: "Gold Nose Pin Ring",
    name: "Classic Gold Nose Pin",
    price: 15000,
    image_url: "https://example.com/images/classic-gold-nose-pin.jpg",
  },
  {
    id: "jewel032",
    category: "Gold Nose Pin Ring",
    name: "Delicate Gold Nose Ring",
    price: 10000,
    image_url: "https://example.com/images/delicate-gold-nose-ring.jpg",
  },
  {
    id: "jewel033",
    category: "Gold Nose Pin Ring",
    name: "Floral Gold Nose Ring",
    price: 22000,
    image_url: "https://example.com/images/floral-gold-nose-ring.jpg",
  },
  {
    id: "jewel034",
    category: "Gold Nose Pin Ring",
    name: "Infinity Gold Nose Pin",
    price: 18000,
    image_url: "https://example.com/images/infinity-gold-nose-pin.jpg",
  },
  {
    id: "jewel035",
    category: "Gold Nose Pin Ring",
    name: "Twist Gold Nose Ring",
    price: 24000,
    image_url: "https://example.com/images/twist-gold-nose-ring.jpg",
  },
  {
    id: "jewel036",
    category: "Gold Nose Pin Ring",
    name: "Star Gold Nose Pin",
    price: 17000,
    image_url: "https://example.com/images/star-gold-nose-pin.jpg",
  },
  {
    id: "jewel037",
    category: "Gold Nose Pin Ring",
    name: "Heart Gold Nose Ring",
    price: 16000,
    image_url: "https://example.com/images/heart-gold-nose-ring.jpg",
  },
  {
    id: "jewel038",
    category: "Gold Nose Pin Ring",
    name: "Bar Gold Nose Pin",
    price: 19000,
    image_url: "https://example.com/images/bar-gold-nose-pin.jpg",
  },
  {
    id: "jewel039",
    category: "Gold Nose Pin Ring",
    name: "Tribal Gold Nose Ring",
    price: 20000,
    image_url: "https://example.com/images/tribal-gold-nose-ring.jpg",
  },
  {
    id: "jewel040",
    category: "Gold Nose Pin Ring",
    name: "Beaded Gold Nose Pin",
    price: 13000,
    image_url: "https://example.com/images/beaded-gold-nose-pin.jpg",
  },
  {
    id: "jewel041",
    category: "Gold Pendant",
    name: "Lotus Gold Pendant",
    price: 42000,
    image_url: "https://example.com/images/lotus-gold-pendant.jpg",
  },
  {
    id: "jewel042",
    category: "Gold Pendant",
    name: "Moon and Star Gold Pendant",
    price: 46000,
    image_url: "https://example.com/images/moon-and-star-gold-pendant.jpg",
  },
  {
    id: "jewel043",
    category: "Gold Pendant",
    name: "Angel Wing Gold Pendant",
    price: 44000,
    image_url: "https://example.com/images/angel-wing-gold-pendant.jpg",
  },
  {
    id: "jewel044",
    category: "Gold Pendant",
    name: "Evil Eye Gold Pendant",
    price: 35000,
    image_url: "https://example.com/images/evil-eye-gold-pendant.jpg",
  },
  {
    id: "jewel045",
    category: "Gold Pendant",
    name: "Butterfly Gold Pendant",
    price: 37000,
    image_url: "https://example.com/images/butterfly-gold-pendant.jpg",
  },
  {
    id: "jewel046",
    category: "Gold Pendant",
    name: "Om Symbol Gold Pendant",
    price: 39000,
    image_url: "https://example.com/images/om-symbol-gold-pendant.jpg",
  },
  {
    id: "jewel047",
    category: "Gold Pendant",
    name: "Anchor Gold Pendant",
    price: 41000,
    image_url: "https://example.com/images/anchor-gold-pendant.jpg",
  },
  {
    id: "jewel048",
    category: "Gold Pendant",
    name: "Lock and Key Gold Pendant",
    price: 37000,
    image_url: "https://example.com/images/lock-and-key-gold-pendant.jpg",
  },
  {
    id: "jewel049",
    category: "Gold Pendant",
    name: "Infinity Heart Gold Pendant",
    price: 43000,
    image_url: "https://example.com/images/infinity-heart-gold-pendant.jpg",
  },
  {
    id: "jewel050",
    category: "Gold Pendant",
    name: "Arrow Gold Pendant",
    price: 38000,
    image_url: "https://example.com/images/arrow-gold-pendant.jpg",
  },
  {
    id: "jewel051",
    category: "Gold Nose Pin Ring",
    name: "Lotus Gold Nose Pin",
    price: 25000,
    image_url: "https://example.com/images/lotus-gold-nose-pin.jpg",
  },
  {
    id: "jewel052",
    category: "Gold Nose Pin Ring",
    name: "Butterfly Gold Nose Ring",
    price: 18000,
    image_url: "https://example.com/images/butterfly-gold-nose-ring.jpg",
  },
  {
    id: "jewel053",
    category: "Gold Nose Pin Ring",
    name: "Moon Gold Nose Ring",
    price: 21000,
    image_url: "https://example.com/images/moon-gold-nose-ring.jpg",
  },
  {
    id: "jewel054",
    category: "Gold Nose Pin Ring",
    name: "Sun Gold Nose Pin",
    price: 22000,
    image_url: "https://example.com/images/sun-gold-nose-pin.jpg",
  },
  {
    id: "jewel055",
    category: "Gold Nose Pin Ring",
    name: "Infinity Gold Nose Pin",
    price: 17000,
    image_url: "https://example.com/images/infinity-gold-nose-pin.jpg",
  },
  {
    id: "jewel056",
    category: "Gold Nose Pin Ring",
    name: "Arrow Gold Nose Ring",
    price: 24000,
    image_url: "https://example.com/images/arrow-gold-nose-ring.jpg",
  },
  {
    id: "jewel057",
    category: "Gold Nose Pin Ring",
    name: "Anchor Gold Nose Pin",
    price: 23000,
    image_url: "https://example.com/images/anchor-gold-nose-pin.jpg",
  },
  {
    id: "jewel058",
    category: "Gold Nose Pin Ring",
    name: "Heart Gold Nose Pin",
    price: 19000,
    image_url: "https://example.com/images/heart-gold-nose-pin.jpg",
  },
  {
    id: "jewel059",
    category: "Gold Nose Pin Ring",
    name: "Locket Gold Nose Ring",
    price: 20000,
    image_url: "https://example.com/images/locket-gold-nose-ring.jpg",
  },
  {
    id: "jewel060",
    category: "Gold Nose Pin Ring",
    name: "Cross Gold Nose Pin",
    price: 21000,
    image_url: "https://example.com/images/cross-gold-nose-pin.jpg",
  },
];
